name: Deploy Angular App with Base Href using Bun

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install Bun
      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Step 3: Install Dependencies with Bun
      - name: Install Dependencies
        run: bun install

      # Step 4: Deploy the Angular App
      - name: Deploy Angular App
        run: ng deploy --base-href=/snake/
